### ISSUE TITLE
Pagination component does not handle large number of items

### ISSUE THREAD

**Issue by hampusn** [sitevision/envision#119]
The pagination items will overflow when they cannot be contained within the parent container. This is most likely due to the flexed items not wrapping. This issue will most likely present itself on smaller screens or when there are a larger amount of items in the pager.

<img width="1557" alt="no-flex-wrap" src="https://user-images.githubusercontent.com/588352/70227809-86d43500-1753-11ea-9a06-397163105c21.png">

Adding flex-wrap to the list element will instead create an issue with the borders. See the attachment below.

<img width="868" alt="flex-wrap" src="https://user-images.githubusercontent.com/588352/70227822-8b98e900-1753-11ea-8314-570a1413441c.png">

What kind of strategy/guidelines do you have for ux-patterns? This issue could be solved either by adjusting the flex and border styles, or by adding some kind of interaction powered by javascript. I guess the most simple solution would be to just adjust the styles.

**Comment by robinlagren** [comment]
Thanks for pointing this out.

We will try to improve the default behaviour with some basic flex wrapping (with border issue in mind). 

Generally we try to avoid JS interactions. However, in my opinion should visible pagination items depend on screen width and never wrap. This requires some JS and might be another improvement we should consider.
