### ISSUE TITLE
Icon usage and documentation

### ISSUE THREAD

**Issue by zykadelic** [sitevision/envision#130]
It's not clear from the documentation how you would access the icons in your project. The change from fonts to SVGs made in #33 updates the documentation with a path to the SVG icon sprite, but using the path accessible from within the Jekyll environment. What’s the correct path for usage in, say, a WebApp environment?

**Comment by hampusn** [comment]
I agree that the documentation is lacking regarding this. Try using `/sitevision/envision-icons.svg`.

**Comment by zykadelic** [comment]
Thanks @hampusn, this worked :)
