### ISSUE TITLE
Tab component is not responsive

### ISSUE THREAD

**Issue by popsork** [sitevision/envision#134]
The tab component doesn't seem to be responsive. When I have more tabs than can fit in the viewport, the tabs overflow outside the screen and create side scrolling.

![image](https://user-images.githubusercontent.com/867653/73248207-d1ea5180-41b2-11ea-813c-000bfcfe8678.png)

One way to solve it is to make the tabs `display: block` in smartphone like in this example [1], and maybe make the flex wrap in other sizes.

[1] https://a11y.nicolas-hoffmann.net/tabs/

**Comment by melineric** [comment]
Used your suggestion. You'll have to add a class `env-tabs--column` when  desired breakpoint occurred.

Cheers!
