### ISSUE TITLE
Versioning of Envision in docs

### ISSUE THREAD

**Issue by hampusn** [sitevision/envision#223]
I've seen some version numbers appearing in the docs as of lately. From what I can tell, they seem to be referring to Sitevision and not to Envision. Does that mean the Envision version will be following Sitevision? If that's the case, could the docs benefit from that connection/dependency being more clear?

**Comment by henrikekelof** [comment]
Yes, Envision is tightly connected to Sitevision releases. At the moment, we can't release Envision without releasing a new version of Sitevision. We are working on a way to improve that, we'd like to be able to release new versions of Envision more like apps in the marketplace. When we get there we will use another system for versioning, but this will have to do in the meantime. If you have suggestions on how to label pages/components better we're listening, but we see the labels as a temporary solution only.
