### ISSUE TITLE
Consider switching from icon fonts to svg

### ISSUE THREAD

**Issue by alexandernanberg** [sitevision/envision#32]
Generally icon fonts are not considered best practise any more. Rendering and accessibility are just some problems. 

https://css-tricks.com/icon-fonts-vs-svg/

We have a icon system that bundles all svg files in a directory and creates a sprite. That way we can do this in our HTML

``` html
<svg>
  <use xlink:href="path/to/sprite.svg#icon-name"></use>
</svg>
```

See it in action here
https://github.com/strt/boilerplate

**Comment by albinohrn** [comment]
Fixed in #33
