### ISSUE TITLE
Missing dist/envision-icons.svg blocking startup

### ISSUE THREAD

**Issue by viktor-sarge** [sitevision/envision#374]
Just cloned the project locally, ran 'yarn install' and 'yarn dev'. Envision complains about a missing file at the path "envision/node_modules/envision/dist/envision-icons.svg" and refused to start. I copied it from https://envisionui.io/sitevision/envision-icons.svg and that alleviated the issue.

**Comment by henrikekelof** [comment]
Thanks, we'll look into it. Running `npm run build` once before `yarn dev` might be a workaround in the meantime.

**Comment by viktor-sarge** [comment]
Ah, yes that sounds reasonable. In that case adding that step to the readme would be a working fix :)
