### ISSUE TITLE
Breaking words in env-collapse

### ISSUE THREAD

**Issue by oskarakerlund-consid** [sitevision/envision#417]
The `.env-collapse` class contains rules for both `word-wrap` and `overflow-wrap`, even though `word-wrap` is [just an alias](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) for `overflow-wrap`.

What makes it stranger is that they have different values (`break-word` and `anywhere`)

Also isn't `word-break: normal` contradictory to the above?

See: https://github.com/sitevision/envision/blob/c96db597d830a4ad2b1795f3f484dc76273b5b8c/packages/envision/src/scss/collapse.scss#L6-L8

**Comment by henrikekelof** [comment]
Thanks! `word-wrap` should be removed. It's legacy code for IE11 where "anywhere" wasn't an allowed value.

`word-break:normal` isn't contradictory, it's a different thing.  Look at the note in the page you linked to: "In contrast to word-break, overflow-wrap will only create a break if an entire word cannot be placed on its own line without overflowing."
