### ISSUE TITLE
Envision checkboxes do not trigger browser validation correctly on required fields

### ISSUE THREAD

**Issue by sahinbosnic** [sitevision/envision#439]
I've stumbled upon a possible bug with the checkboxes in Envision. 
Since the input type="checkbox" has some kind of "sr-only" styling, it seems that the browser validation ignores the field being required and handles it as a non visible or perhaps disabled field. I've narrowed it down to the style "margin: -1px;" being the culprit for this issue. I've temporarily fixed the issue by removing the "margin: -1px;" styling which seems to solve the problem while not visibly affecting the design.

I have not tested if this applies to radio buttons as well. 

Tested in Chrome Browser on a Webapp 2 React client side rendered application

```
<fieldset className="env-form-element__control">
    <div className="env-checkbox">
    
        {/* Inline styling to remove validation bug */}
        <input type="checkbox" style={{ margin: "initial" }} name="consent" id="cb1" required />
        
        <label className="env-form-element__label" htmlFor="cb1">
            <span className="env-checkbox__fake"></span>
            <span className="env-checkbox__label">{data.consentText}</span>
        </label>
    </div>
</fieldset>
```

**Comment by henrikekelof** [comment]
There will be a new checkbox variant available in Sitevision 2024.08.1 that does not use additional markup. I have not been able to reproduce the error for the old checkbox component, and the margin for the input is 0 so I'm not sure where the -1 comes from. Please try the new component when released later this summer and get back to us if the problem persists.
