### ISSUE TITLE
Contenteditable element, placeholder wont disappear on focus Safari

### ISSUE THREAD

**Issue by sahinbosnic** [sitevision/envision#443]
There's a bug with the contenteditable element. The placeholder seems to disappear perfectly in all browsers but Safari on Focus.
This requires us to add a custom handling for the placeholder on Safari

https://envisionui.io/components/form/

![image](https://github.com/sitevision/envision/assets/1994204/6af41d4a-336d-48f9-9e54-c429ad67f3f5)

**Comment by henrikekelof** [comment]
There is a new version of the component coming out in Sitevision 2024.08.1 that will partially solve this issue. It uses the aria-placeholder attribute instead of an extra HTML. When released you should switch over to that.
