### ISSUE TITLE
Consider replacing jQuery with a nicer alternative (React, Vue etc)

### ISSUE THREAD

**Issue by alexandernanberg** [sitevision/envision#51]
It could be just my personal opinion but I think working with jQuery is pretty outdated. More and more websites are adapting these new technologies and seeing great benefits. Eg aftonbladet.se is now built in React. 

It would solve problems with colliding jQuery versions as well. 

So my recommendation is to check out both React and Vue and test which fits best for you. I personally like direction React has taken.

**Comment by robinlagren** [comment]
Good opinion. 

We will consider removing jQuery as a dependency and replace it w/ vanilla js (to avoid any kind of colliding versions).
