### ISSUE TITLE
Docs contains faulty css-classes which uses prefix sv- instead of env- (legacy code?)

### ISSUE THREAD

**Issue by hampusn** [sitevision/envision#72]

**Comment by albinohrn** [comment]
I think it's just old habbits always prefixing with `sv-`. I think the docs should use no prefix or an own prefix like `doc-` to clarify that those classes are not in the distribution.

**Comment by hampusn** [comment]
Yo @albinohrn !

I should probably have posted some references but I assumed no one would comment this before I had a PR with fix ready. :)

I agree about the generic styling for the actual website. I'm pretty sure those that I found are supposed to be "envision classes". See this commit for reference: https://github.com/hampusn/envision/commit/7fac93888ec06cf1bcd7553814ef3d0978ba15ab

**Comment by albinohrn** [comment]
Yep! Looks like you've found legacy code there that should be changed to `env-`! Good catch!

**Comment by hampusn** [comment]
Yay! :)
