### ISSUE TITLE
Specify browser support (autoprefixer & babel-preset-env)

### ISSUE THREAD

**Issue by alexandernanberg** [sitevision/envision#76]
I've not found any specifications on what browsers Envision intend to support. 

We should probably define them in both `autoprefixer` and `babel-preset-env` to avoid obsolete/unnecessary vendor prefixes etc

**Comment by hampusn** [comment]
Should imho also be mentioned in README :)

**Comment by hampusn** [comment]
It looks like this was solved 2017. Maybe it should be closed to clean up the list of open issues? :)
