### ISSUE TITLE
eslint requires unix style linebreaks

### ISSUE THREAD

**Issue by martinahlqvist** [sitevision/envision#80]
Currently there is a requirement that the line break style is unix or else an error is returned. For PC users this could perhaps be set to off instead or at least a warning. Causes errors today and prevents build. If set to off in .eslintrc.json it builds.

**Comment by albinohrn** [comment]
If you use an editor such as VSCode or similar you can install a plugin called [.editorconfig](http://editorconfig.org/). This plugin will instruct your editor to use the correct line breaks according to the `.editorconfig` file in the repo. It will work on windows as well.
